# Generated by Django 4.2.3 on 2023-07-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar_user_description_user_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
