# Generated by Django 4.2.3 on 2023-07-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
    ]
